
@host = http://localhost:8080
@userId=2

### 헬로월드 i18n
GET http://localhost:8080/hello-world-internationalized
Accept: application/json
Accept-Language: ko
### 404 반환 예시
GET {{host}}/users/13123
Accept: application/json


### GET All users
GET {{host}}/users
Accept: application/xml

### GET user by ID
GET {{host}}/users/{{userId}}


### Post 요청 테스트
POST {{host}}/users
Content-Type: application/json

{
  "name": "soroso",
  "birthDate": "2032-01-07"
}

### Remove user by id
DELETE {{host}}/users/3

### Versioning test용(Header Versioning 1)
GET {{host}}/person/header
X-API-VERSION:1

### Versioning test용(Header Versioning 2)
GET {{host}}/person/header
X-API-VERSION:2

### Versioning test용(Accept Header Versioning 1)
GET {{host}}/person/accept
Accept: application/vnd.company.app-v1+json

### Versioning test용(Accept Header Versioning 2)
GET {{host}}/person/accept
Accept: application/vnd.company.app-v2+json