### 404 반환 예시
GET http://localhost:8080/users/13123
Accept: application/json


### GET All users
GET http://localhost:8080/users


### Post 요청 테스트
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "soroso1",
  "birthDate": "2000-01-07"
}

### Remove user by id
DELETE http://localhost:8080/users/3
